name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version}}
        uses: actions.node@v4
        with: 
           node-version: ${{ matrix.node-version }}
           cache: npm
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
