name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  test-npm-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Run npm security check
        run : npm audit

  test-integration:
    needs: test-npm-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test

