name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      #- name: Setup Node 18
       # uses: actions/setup-node@v4
        #with:
         # node-version: 18
          #cache: 'npm'
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
